export const validationCases = [
  'A1 Create User',
  'A2 Duplicate Email',
  'A3 Invalid User Data',
  'A4 Create Workspace',
  'A5 Duplicate Slug',
  'A6 Create Project',
  'A7 Delete Project',
  'A8 Create Task',
  'A9 Create Task Without Project',
  'A10 Negative Duration',
  'A11 Parent Task Hierarchy',
  'A12 Create Dependency',
  'A13 Dependency With Missing Task',
  'A14 Duplicate Dependency',
  'A15 Self Dependency',
  'A16 Viewer Creates Task',
  'A17 Admin Creates Task',
  'A18 Soft Delete Task',
  'A19 Query Active Tasks',
  'A20 Update Task',
  'B1 Store Duration',
  'B2 Store Dependency Type',
  'B3 Store Lag',
  'B4 Store CPM Snapshot',
  'C1 Save Layout',
  'C2 Retrieve Layout',
  'D1 Fresh Database Migration',
  'D2 Upgrade Migration',
  'D3 Seed Script',
] as const;

export const benchmarkCases = [
  'A1 Small Graph',
  'A2 Medium Graph',
  'A3 Large Graph',
  'A4 Very Large Graph',
  'A5 Extreme Graph',
  'B1 Long Chain',
  'B2 Wide Graph',
  'B3 Diamond Cascade',
  'B4 Multi-Level Tree',
  'B5 Dense DAG',
  'C1 Large Valid DAG',
  'C2 Large Graph With Hidden Cycle',
  'C3 Duplicate Dependency Explosion',
  'D1 Single Critical Path',
  'D2 Multiple Critical Paths',
  'D3 Highly Parallel Graph',
  'E1 100 Nodes',
  'E2 1000 Nodes',
  'E3 5000 Nodes',
  'E4 10000 Nodes',
  'F1 Construction Project',
  'F2 Software Development Project',
  'F3 BAJA Vehicle Project',
  'G1 Single Run',
  'G2 100 Consecutive Runs',
  'G3 1000 Consecutive Runs',
  'H1 Add Task',
  'H2 Remove Task',
  'H3 Change Duration',
  'I1 CPM Only',
] as const;
