export type ValidationCase = {
  id: string;
  area: 'schema' | 'crud' | 'persistence' | 'migration';
  title: string;
  expectedOutcome: string;
};

export const validationCases = [
  { id: 'A1', area: 'schema', title: 'Create User', expectedOutcome: 'Success' },
  { id: 'A2', area: 'schema', title: 'Duplicate Email', expectedOutcome: 'Unique constraint violation' },
  { id: 'A3', area: 'schema', title: 'Invalid User Data', expectedOutcome: 'Validation error' },
  { id: 'A4', area: 'crud', title: 'Create Workspace', expectedOutcome: 'Success' },
  { id: 'A5', area: 'schema', title: 'Duplicate Slug', expectedOutcome: 'Unique constraint violation' },
  { id: 'A6', area: 'crud', title: 'Create Project', expectedOutcome: 'Success' },
  { id: 'A7', area: 'crud', title: 'Delete Project', expectedOutcome: 'Cascade rules preserved' },
  { id: 'A8', area: 'crud', title: 'Create Task', expectedOutcome: 'Success' },
  { id: 'A9', area: 'schema', title: 'Create Task Without Project', expectedOutcome: 'Foreign key violation' },
  { id: 'A10', area: 'schema', title: 'Negative Duration', expectedOutcome: 'Validation error' },
  { id: 'A11', area: 'crud', title: 'Parent Task Hierarchy', expectedOutcome: 'Parent-child relation works' },
  { id: 'A12', area: 'crud', title: 'Create Dependency', expectedOutcome: 'Success' },
  { id: 'A13', area: 'schema', title: 'Dependency With Missing Task', expectedOutcome: 'Foreign key violation' },
  { id: 'A14', area: 'schema', title: 'Duplicate Dependency', expectedOutcome: 'Rejected' },
  { id: 'A15', area: 'schema', title: 'Self Dependency', expectedOutcome: 'Rejected' },
  { id: 'A16', area: 'crud', title: 'Viewer Creates Task', expectedOutcome: 'Permission denied' },
  { id: 'A17', area: 'crud', title: 'Admin Creates Task', expectedOutcome: 'Success' },
  { id: 'A18', area: 'crud', title: 'Soft Delete Task', expectedOutcome: 'deletedAt populated' },
  { id: 'A19', area: 'crud', title: 'Query Active Tasks', expectedOutcome: 'Deleted tasks excluded' },
  { id: 'A20', area: 'crud', title: 'Update Task', expectedOutcome: 'Activity entry created' },
  { id: 'B1', area: 'persistence', title: 'Store Duration', expectedOutcome: 'Correct persistence' },
  { id: 'B2', area: 'persistence', title: 'Store Dependency Type', expectedOutcome: 'Correct retrieval' },
  { id: 'B3', area: 'persistence', title: 'Store Lag', expectedOutcome: 'Correct persistence' },
  { id: 'B4', area: 'persistence', title: 'Store CPM Snapshot', expectedOutcome: 'Critical path persisted' },
  { id: 'C1', area: 'persistence', title: 'Save Layout', expectedOutcome: 'Coordinates stored' },
  { id: 'C2', area: 'persistence', title: 'Retrieve Layout', expectedOutcome: 'Coordinates restored' },
  { id: 'D1', area: 'migration', title: 'Fresh Database Migration', expectedOutcome: 'Success' },
  { id: 'D2', area: 'migration', title: 'Upgrade Migration', expectedOutcome: 'No data loss' },
  { id: 'D3', area: 'migration', title: 'Seed Script', expectedOutcome: 'Sample data inserted' },
] as const satisfies readonly ValidationCase[];

export const benchmarkCases = [
  'A1 Small Graph',
  'A2 Medium Graph',
  'A3 Large Graph',
  'A4 Very Large Graph',
  'A5 Extreme Graph',
  'B1 Long Chain',
  'B2 Wide Graph',
  'B3 Diamond Cascade',
  'B4 Multi-Level Tree',
  'B5 Dense DAG',
  'C1 Large Valid DAG',
  'C2 Large Graph With Hidden Cycle',
  'C3 Duplicate Dependency Explosion',
  'D1 Single Critical Path',
  'D2 Multiple Critical Paths',
  'D3 Highly Parallel Graph',
  'E1 100 Nodes',
  'E2 1000 Nodes',
  'E3 5000 Nodes',
  'E4 10000 Nodes',
  'F1 Construction Project',
  'F2 Software Development Project',
  'F3 BAJA Vehicle Project',
  'G1 Single Run',
  'G2 100 Consecutive Runs',
  'G3 1000 Consecutive Runs',
  'H1 Add Task',
  'H2 Remove Task',
  'H3 Change Duration',
  'I1 CPM Only',
] as const;
