'use client';

import { useQuery } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import { format, differenceInDays, addDays } from 'date-fns';
import { Calendar } from 'lucide-react';

export default function GanttPage() {
  const params = useParams();
  const projectId = params.projectId as string;

  const { data: tasks = [], isLoading } = useQuery({
    queryKey: ['tasks', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/v1/projects/${projectId}/tasks`);
      if (!res.ok) throw new Error('Failed to fetch tasks');
      return res.json();
    }
  });

  if (isLoading) {
    return <div className="p-8 text-slate-500">Loading Gantt chart...</div>;
  }

  // Filter tasks that have dates scheduled by CPM
  const scheduledTasks = tasks.filter((t: any) => t.startDate && t.endDate);

  if (scheduledTasks.length === 0) {
    return (
      <div className="p-8 flex flex-col items-center justify-center h-full text-center">
        <div className="w-16 h-16 bg-slate-100 text-slate-400 rounded-full flex items-center justify-center mb-4">
          <Calendar size={32} />
        </div>
        <h3 className="text-lg font-medium text-slate-900 mb-2">No Schedule Available</h3>
        <p className="text-slate-500 max-w-md">
          Tasks need to be scheduled by the Critical Path Engine before they appear on the Gantt chart. Head over to the Graph tab and run the CPM Engine.
        </p>
      </div>
    );
  }

  // Find min and max dates
  const minDate = new Date(Math.min(...scheduledTasks.map((t: any) => new Date(t.startDate).getTime())));
  const maxDate = new Date(Math.max(...scheduledTasks.map((t: any) => new Date(t.endDate).getTime())));
  const totalDays = Math.max(1, differenceInDays(maxDate, minDate) + 1);

  // Generate date headers
  const dates = Array.from({ length: totalDays }).map((_, i) => addDays(minDate, i));

  return (
    <div className="p-8 h-full flex flex-col bg-white">
      <div className="mb-6">
        <h2 className="text-xl font-bold text-slate-900">Project Timeline</h2>
        <p className="text-sm text-slate-500 mt-1">Generated by CPM Engine</p>
      </div>

      <div className="flex-1 overflow-auto border border-slate-200 rounded-xl">
        <div className="min-w-max">
          {/* Header */}
          <div className="flex border-b border-slate-200 bg-slate-50 sticky top-0 z-10">
            <div className="w-64 flex-shrink-0 p-3 border-r border-slate-200 font-semibold text-xs text-slate-600 flex items-end">
              Task Name
            </div>
            <div className="flex">
              {dates.map((date, i) => (
                <div key={i} className="w-12 flex-shrink-0 border-r border-slate-200 p-2 flex flex-col items-center justify-center">
                  <span className="text-[10px] text-slate-400 uppercase font-medium">{format(date, 'MMM')}</span>
                  <span className="text-sm font-semibold text-slate-700">{format(date, 'd')}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Rows */}
          <div className="relative">
            {scheduledTasks.map((task: any) => {
              const taskStart = new Date(task.startDate);
              const taskEnd = new Date(task.endDate);
              
              const startOffsetDays = differenceInDays(taskStart, minDate);
              const durationDays = differenceInDays(taskEnd, taskStart) + 1; // +1 to include end day
              
              const leftOffset = startOffsetDays * 48; // 48px is w-12
              const width = durationDays * 48;

              // Simple heuristic to color critical path differently if we had that flag on task
              // For now, use a default blue.
              const isCritical = false; // We can pass this flag from backend if available

              return (
                <div key={task.id} className="flex border-b border-slate-100 hover:bg-slate-50 group">
                  <div className="w-64 flex-shrink-0 p-3 border-r border-slate-200 text-sm font-medium text-slate-700 truncate bg-white group-hover:bg-slate-50 z-10 sticky left-0">
                    {task.title}
                  </div>
                  <div className="relative flex-1 flex" style={{ width: totalDays * 48 }}>
                    {/* Background grid lines */}
                    {dates.map((_, i) => (
                      <div key={i} className="w-12 flex-shrink-0 border-r border-slate-50 h-full absolute top-0 bottom-0" style={{ left: i * 48 }} />
                    ))}
                    
                    {/* Gantt Bar */}
                    <div 
                      className="absolute top-2 h-8 rounded-md shadow-sm flex items-center px-2 text-xs font-semibold text-white truncate overflow-hidden transition-all duration-200 hover:brightness-110 cursor-pointer"
                      style={{
                        left: leftOffset,
                        width: width - 4, // slight margin
                        backgroundColor: isCritical ? '#ef4444' : '#3b82f6'
                      }}
                      title={`${task.title} (${durationDays} days)`}
                    >
                      {durationDays > 1 ? task.title : ''}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
