'use client';

import { useQuery } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import { format, differenceInDays, addDays } from 'date-fns';
import { Calendar } from 'lucide-react';

const getGanttStatusColor = (state: string) => {
  switch (state) {
    case 'BACKLOG': return 'bg-slate-300 text-slate-700 border-slate-400';
    case 'TODO': return 'bg-slate-400 text-white border-slate-500';
    case 'IN_PROGRESS': return 'bg-blue-500 text-white border-blue-600';
    case 'REVIEW': return 'bg-amber-400 text-amber-900 border-amber-500';
    case 'DONE': return 'bg-emerald-500 text-white border-emerald-600';
    case 'CANCELED': return 'bg-red-400 text-white border-red-500';
    default: return 'bg-blue-500 text-white border-blue-600';
  }
};

export default function GanttPage() {
  const params = useParams();
  const projectId = params.projectId as string;

  const { data: tasks = [], isLoading: tasksLoading } = useQuery({
    queryKey: ['tasks', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/v1/projects/${projectId}/tasks`);
      if (!res.ok) throw new Error('Failed to fetch tasks');
      return res.json();
    }
  });

  const { data: cpmResults, isLoading: cpmLoading } = useQuery({
    queryKey: ['cpmResults', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/v1/projects/${projectId}/cpm/results`);
      if (!res.ok) {
        if (res.status === 404) return null;
        throw new Error('Failed to fetch CPM results');
      }
      return res.json();
    }
  });

  const isLoading = tasksLoading || cpmLoading;

  if (isLoading) {
    return <div className="p-8 text-slate-500">Loading Gantt chart...</div>;
  }

  // Filter tasks that have dates scheduled by CPM
  const scheduledTasks = tasks.filter((t: any) => t.startDate && t.endDate);

  if (scheduledTasks.length === 0) {
    return (
      <div className="p-8 flex flex-col items-center justify-center h-full text-center">
        <div className="w-16 h-16 bg-slate-100 text-slate-400 rounded-full flex items-center justify-center mb-4">
          <Calendar size={32} />
        </div>
        <h3 className="text-lg font-medium text-slate-900 mb-2">No Schedule Available</h3>
        <p className="text-slate-500 max-w-md">
          Tasks need to be scheduled by the Critical Path Engine before they appear on the Gantt chart. Head over to the Graph tab and run the CPM Engine.
        </p>
      </div>
    );
  }

  // Find min and max dates
  const minDate = new Date(Math.min(...scheduledTasks.map((t: any) => new Date(t.startDate).getTime())));
  const maxDate = new Date(Math.max(...scheduledTasks.map((t: any) => new Date(t.endDate).getTime())));
  const totalDays = Math.max(1, differenceInDays(maxDate, minDate) + 1);

  // Generate date headers
  const dates = Array.from({ length: totalDays }).map((_, i) => addDays(minDate, i));

  return (
    <div className="p-8 h-full flex flex-col bg-white">
      <div className="mb-6 flex justify-between items-end">
        <div>
          <h2 className="text-xl font-bold text-slate-900">Project Timeline</h2>
          <p className="text-sm text-slate-500 mt-1">Generated by CPM Engine</p>
        </div>
        <div className="flex gap-4 text-xs">
          <div className="flex items-center gap-1.5"><div className="w-3 h-3 rounded bg-slate-400"></div><span className="text-slate-600">Todo</span></div>
          <div className="flex items-center gap-1.5"><div className="w-3 h-3 rounded bg-blue-500"></div><span className="text-slate-600">In Progress</span></div>
          <div className="flex items-center gap-1.5"><div className="w-3 h-3 rounded bg-amber-400"></div><span className="text-slate-600">Review</span></div>
          <div className="flex items-center gap-1.5"><div className="w-3 h-3 rounded bg-emerald-500"></div><span className="text-slate-600">Done</span></div>
          <div className="flex items-center gap-1.5 border-l border-slate-200 pl-4"><div className="w-3 h-3 rounded bg-slate-300 ring-2 ring-red-500 ring-offset-1"></div><span className="text-slate-900 font-medium">Critical</span></div>
        </div>
      </div>

      <div className="flex-1 overflow-auto border border-slate-200 rounded-xl">
        <div className="min-w-max">
          {/* Header */}
          <div className="flex border-b border-slate-200 bg-slate-50 sticky top-0 z-10">
            <div className="w-64 flex-shrink-0 p-3 border-r border-slate-200 font-semibold text-xs text-slate-600 flex items-end">
              Task Name
            </div>
            <div className="flex">
              {dates.map((date, i) => (
                <div key={i} className="w-12 flex-shrink-0 border-r border-slate-200 p-2 flex flex-col items-center justify-center">
                  <span className="text-[10px] text-slate-400 uppercase font-medium">{format(date, 'MMM')}</span>
                  <span className="text-sm font-semibold text-slate-700">{format(date, 'd')}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Rows */}
          <div className="relative">
            {scheduledTasks.map((task: any) => {
              const taskStart = new Date(task.startDate);
              const taskEnd = new Date(task.endDate);
              
              const startOffsetDays = differenceInDays(taskStart, minDate);
              const durationDays = differenceInDays(taskEnd, taskStart) + 1; // +1 to include end day
              
              const leftOffset = startOffsetDays * 48; // 48px is w-12
              const width = durationDays * 48;

              // Simple heuristic to color critical path differently if we had that flag on task
              // For now, use a default blue.
              const taskDetails = cpmResults?.details?.taskDetails || {};
              const details = taskDetails[task.id];
              const isCritical = details?.isCritical || false;

              return (
                <div key={task.id} className="flex border-b border-slate-100 hover:bg-slate-50 group">
                  <div className="w-64 flex-shrink-0 p-3 border-r border-slate-200 text-sm font-medium text-slate-700 truncate bg-white group-hover:bg-slate-50 z-10 sticky left-0">
                    <div className="flex items-center gap-2">
                      {isCritical && <div className="w-1.5 h-1.5 rounded-full bg-red-500 flex-shrink-0" title="Critical Task" />}
                      <span className="truncate">{task.title}</span>
                    </div>
                  </div>
                  <div className="relative flex-1 flex" style={{ width: totalDays * 48 }}>
                    {/* Background grid lines */}
                    {dates.map((_, i) => (
                      <div key={i} className="w-12 flex-shrink-0 border-r border-slate-50 h-full absolute top-0 bottom-0" style={{ left: i * 48 }} />
                    ))}
                    
                    {/* Gantt Bar */}
                    <div 
                      className={`absolute top-2 h-8 rounded-md shadow-sm flex items-center px-2 text-xs font-semibold truncate overflow-hidden transition-all duration-200 hover:brightness-110 cursor-pointer border ${getGanttStatusColor(task.state)} ${
                        isCritical ? 'ring-2 ring-red-500 ring-offset-1 ring-offset-white' : ''
                      }`}
                      style={{
                        left: leftOffset,
                        width: width - 4, // slight margin
                      }}
                      title={
                        details
                          ? `Task: ${task.title}\nDuration: ${task.duration}d\nES: ${details.es} | EF: ${details.ef}\nLS: ${details.ls} | LF: ${details.lf}\nSlack: ${details.slack}\nCritical: ${isCritical ? 'Yes' : 'No'}`
                          : `${task.title} (${durationDays} days)`
                      }
                    >
                      {durationDays > 1 ? task.title : ''}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
